#page title
page_title: trepar - the climber's guide and social network # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://app.trepar.app # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://app.trepar.app # Enter Google Play Store URL.
presskit_download_link:
  https://app.trepar.app # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: https://app.trepar.app/assets/icons/icon-512x512.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: trepar # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: The climber's social network

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: ramon.wtf
your_link: https://ramon.wtf
your_city: Mallorca
email_address: hello@ramon.wtf
facebook_username:
instagram_username: ramonvg
twitter_username: ramonwhatever
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Explora zonas
    description: Explora las zonas y sus sectores. Encuentra las rutas clasificadas por dificultad.
    fontawesome_icon_name: mountain

  - title: Registra tus ascensos
    description: Guarda cada ruta que has ascendido. Elige si la has escalado a vista, flash o redpoint.
    fontawesome_icon_name: check-circle

  - title: Interacciona
    description: Sigue los ascensos de tus amigos. Interactua con ellos.
    fontawesome_icon_name: users

  - title: Añade rutas
    description: Añade rutas a la aplicación para que todos podamos escalarlas.
    fontawesome_icon_name: hands-helping

  - title: Encuentra las direcciones a tu sector
    description: Cada zona y sector tienen sus coordenads GPS para que puedas llegar fácilmente.
    fontawesome_icon_name: directions

  - title: Internacionalización
    description: La aplicación está disponible en castellano, inglés y catalán.
    fontawesome_icon_name: language

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/header.jpg # Replace with alternative image path or image URL.
cover_image_mobile: assets/header_mobile.jpg # Replace with alternative image path or image URL.

cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#0071bc"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#0071bc"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-analytics

google_analytics: UA-154908198-1
